ts-libvirt-build: initscript should depend on xenstored service
In order that xencommons is guarenteed to have been started before
libvirtd. Otherwise sometimes libvirt can be started first resulting
in:
	error: invalid argument: unsupported config type xen-xl

Because xen wasn't available when libvirt started.

Signed-off-by: Ian Campbell <ian.campbell@citrix.com>
Acked-by: Ian Jackson <ian.jackson@eu.citrix.com>